catalog/urls.py
from django.urls import path

from catalog import views

app_name = 'catalog'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('categoria/<int:pk>/', views.CategoryProductList.as_view(), name='category_list'),
    path('crear/', views.ProductCreateView.as_view(), name='product_create')
]

onlineshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField, OneToOneField


class Category(models.Model):
    name = models.CharField(max_length=48, unique=True, verbose_name='nombre')

    is_active = models.BooleanField(default=True, verbose_name='está activa')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='categoria')

    name = models.CharField(max_length=128, verbose_name='nombre')
    
    short_description = models.TextField(max_length=128, verbose_name='descripción corta')

    large_description = models.TextField(max_length=480, verbose_name='descripción larga')

    price = models.IntegerField(verbose_name='precio') 

    quantity = models.IntegerField(verbose_name='cantidad')

    is_active = models.BooleanField(default=True, verbose_name='está activo')

    image = models.ImageField(verbose_name='imagen', upload_to='products')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')

    def __str__(self):
        return f'{self.name} - {self.price} - {self.category}'

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'


class ProductImage(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='product')

    image = models.ImageField(verbose_name='imagen', upload_to='products_detail')

    class Meta:
        verbose_name = 'imagen del producto'
        verbose_name_plural = 'imagen de los productos'

order/models.py
from django.db import models

# Create your models here.

catalog/forms.py
from django.forms import ModelForm
from catalog.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'category',
            'name',
            'short_description',
            'large_description',
            'price',
            'quantity',
            'image'
        ]

catalog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from catalog.forms import ProductForm
from catalog.models import Category, Product


class BaseView:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'categories': Category.objects.filter(is_active=True),
            'logo': 'Tienda Virtual'
        })
        return context


class ProductListView(BaseView, ListView):
    model = Product

    def get_queryset(self):
        # select * from Product where is_active=True
        return Product.objects.filter(is_active=True)

    
class ProductDetailView(BaseView, DetailView):
    model = Product


class CategoryProductList(BaseView, ListView):
    model = Product

    def get_queryset(self):
        return Product.objects.filter(is_active=True, category=self.kwargs['pk'])


class ProductCreateView(BaseView, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

order/views.py
from django.shortcuts import render

# Create your views here.

catalog/templates/catalog/product_detail.html
{% extends 'layout/base.html' %}
{% load static humanize %}
{% block content %}
<div class="container mx-auto">
    <div class="grid grid-cols-3 gap-10 py-10">
        <div class="col-span-2">                
            <div class="carousel relative shadow-2xl bg-white">
                <div class="carousel-inner relative overflow-hidden w-full">
                    {% for item in object.productimage_set.all %}
                        <input class="carousel-open" type="radio" id="carousel-{{forloop.counter}}" name="carousel" aria-hidden="true" hidden="" checked="checked">
                        <div class="carousel-item absolute opacity-0" style="height:50vh;">
                            <img class="mx-auto" src={{ item.image.url }} alt="">
                        </div>
                        {% if forloop.first %}
                        <label for="carousel-3" class="prev control-1 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
                        <label for="carousel-2" class="next control-1 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>
                        {% elif forloop.last %}
                        <label for="carousel-2" class="prev control-3 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
                        <label for="carousel-1" class="next control-3 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>
                        {% else %}                            
                        <label for="carousel-1" class="prev control-2 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
                        <label for="carousel-3" class="next control-2 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label> 
                        {% endif %} 
                    {% endfor %}
                    {% for item in object.productimage_set.all %}
                    <ol class="carousel-indicators">
                        <li class="inline-block mr-3">
                            <label for="carousel-{{forloop.counter}}" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
                        </li>
                    </ol>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="border-2 border-gray-300 rounded-lg p-2">
            <p class="text-xl font-semibold">
            {{ object.name|upper }}
            </p>
            <p class="text-3xl font-normal py-10">
            $ {{ object.price|intcomma }}
            </p>
            <p class="text-sm font-ligth py-20">
            {{ object.short_description }}
            </p>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="container mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="py-3">
                <button class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" type="submit">Enviar</button>            
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'layout/base.html' %}
{% load static humanize %}
{% block content %}
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
    {% for product in object_list %}
    <div class="rounded overflow-hidden shadow-lg">
        <a href="{% url 'catalog:product_detail' product.id %}">
            <img class="w-full" src="{{ product.image.url }}" alt="{{ product.name }}">
        </a>
        <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">{{ product.name }}</div>
            <p class="text-gray-700 text-base">
            {{ product.short_description }}
            </p>
            <p class="text-gray-900 text-base">
            COP $ {{ product.price|intcomma }}
            </p>
        </div>       
    </div> 
    {% endfor %}
</div>
{% endblock %}

onlineshop/templates/layout/base.html
{% load static humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OnlineShop</title>
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">  
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">  
    <!-- CDN Alpine -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
</head>
<body>
    <div class="w-full text-gray-700 bg-blue-500 dark-mode:text-gray-200 dark-mode:bg-gray-800">
        <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
            <div class="p-4 flex flex-row items-center justify-between">
            <a href="#" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">{{ logo }}</a>
            <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
                <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
            </button>
            </div>
            <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
                <div @click.away="open = false" class="relative" x-data="{ open: false }">
                    <button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:focus:bg-gray-600 dark-mode:hover:bg-gray-600 md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-green-400 focus:bg-green-500 focus:outline-none focus:shadow-outline">
                    <span>CATEGORÍAS</span>
                    <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    </button>
                    <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
                        <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">                   
                            {% for category in categories %}
                            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'catalog:category_list' category.id %}">
                                {{ category.name }}
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>    
            </nav>
        </div>
    </div>
    {% block content %}{% endblock %}
</div> 
</body>
</html>